project:
  type: book

engine: knitr

book:
  title: "A2CPS Starter Kits"
  author: "A2CPS Consortium"
  date: today
  chapters:
    - index.qmd
    - raw-mri.qmd
    - freesurfer.qmd
    - faq.qmd
    - references.qmd
  appendices:
    - bids-qc-joining.qmd

bibliography: references.bib
csl: apa.csl

execute:
  freeze: auto  # re-render only when source changes
  cache: true

format:
  html:
    theme: cosmo
    df-print: kable
    citation-location: margin
    reference-location: margin


