project:
  type: book

engine: knitr

book:
  title: "A2CPS Starter Kits"
  author: "A2CPS Consortium"
  date: today
  chapters:
    - index.qmd
    - part: "Omics"
      chapters:
        - snps.qmd
    - part: "MRI"
      chapters:
        - raw-mri.qmd
        - freesurfer.qmd
        - neural-pain-signatures.qmd
    - faq.qmd
    - references.qmd
  appendices:
    - bids-qc-joining.qmd
    - ids.qmd
    - nda-mri.qmd

bibliography: references.bib
csl: apa.csl

execute:
  freeze: auto  # re-render only when source changes
  cache: true

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    df-print: kable
    citation-location: margin
    reference-location: margin

