project:
  type: book

engine: knitr

book:
  title: "A2CPS Starter Kits"
  author: "A2CPS Consortium"
  date: today
  chapters:
    - index.qmd
    - snps.qmd
    - raw-mri.qmd
    - freesurfer.qmd
    - brainager.qmd
    - cat12.qmd
    - fcn.qmd
    - neural-pain-signatures.qmd
    - faq.qmd
    - references.qmd
  appendices:
    - bids-qc-joining.qmd
    - ids.qmd
    - nda-mri.qmd
    - psycho_social_biomarker_impute.qmd
    - biospecimenCRF_quality_checks_and_reformat.qmd
    - FuntionalCRF_data_quality_checks_and_reformat.qmd
    - ImagingCRF_data_quality_checks_and_reformat.qmd
    - QSTCRF_data_quality_checks_and_reformat.qmd

bibliography: references.bib
csl: apa.csl

execute:
  freeze: auto  # re-render only when source changes
  cache: true
  warning: false
  message: false

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    df-print: kable
    citation-location: margin
    reference-location: margin

