# FAQ {.unnumbered}

- Q: How do I access the data?
  - A: Please see [this page on our website](https://a2cps.org/researchers/accessing-our-data/).

- Q: After reviewing the kit, I still have questions. Who should I contact?
  - A: For questions about a kit itself (e.g., an error in an example, or a request for another one), please open an issue on the [starter kits repository](https://github.com/a2cps/starterkits/issues). For questions about the data, or about how to access them, please see [this page on our website](https://a2cps.org/researchers/accessing-our-data/).

- Q: I am not familiar with `R`. What are a few good resources.
  - A: A great introduction to data analysis in R is the [R for Data Science](https://r4ds.hadley.nz/) book. Many of the starter kits rely on the [tidyverse](https://www.tidyverse.org/), which is covered in that book. 

- Q: I'm seeing what appears to be a set of related technologies, including parquet files, the Arrow format, and hive-style partitioning. Where can I find out more information about these?
  - A: Please see [this chapter in the R for Data Science book](https://r4ds.hadley.nz/arrow.html). See also [this series of posts by Danielle Navarro](https://blog.djnavarro.net/#category=Apache%20Arrow). For reading and working with these files, many kits specifically use the [duckplyr](https://duckplyr.tidyverse.org/index.html) package.

- Q: Where can I find out more information about Chronic Pain, and how A2CPS will help?
  - A: Please see [this page on our website](https://a2cps.org/researchers/a2cps-study-details/).
