
```{r setup}
#| include: false
library(readr)
```


# QSIPrep

Before being analyzed, structural and diffusion neuroimaging data undergo a core set of preprocessing steps. These steps include head motion correction, distortion correction, denoising, Gibbs unringing, coregistration (between structural and functional), and several others. The A2CPS project does this preprocessing with [QSIPrep](https://qsiprep.readthedocs.io/en/latest). The QSIPrep derivatives are useful when assessing the quality of preprocessing, or implementing a custom reconstruction or tracking algorithm. 

## Starting Project

### Locate Data

{{< include _snippets/mri-location.qmd >}}

The QSIPrep derivatives are underneath `derivatives/qsiprep-V1`. Let's take a look.

```{bash}
#| eval: false
$ ls derivatives/qsiprep-V1 | head
sub-10003
sub-10003.html
sub-10008
sub-10008.html
sub-10010
sub-10010.html
sub-10011
sub-10011.html
sub-10013
sub-10013.html
```

### Extract Data

For a detailed description of the files produced by QSIPrep, please review [their documentation](https://qsiprep.readthedocs.io/en/latest/preprocessing.html#outputs-of-qsiprep).

## Considerations While Working on the Project

### Variability Across Scanners

{{< include _snippets/mri-scanner-variability.qmd >}}

### Data Quality

{{< include _snippets/mri-qc.qmd >}}

### Data Generation

These outputs were generated by the [qsiprep_app](https://github.com/a2cps/mri_imaging_pipeline/tree/master/qsiprep_app). 

Preprocessing was performed using *QSIPrep* 0.21.5.dev0+g36b93fe.d20240504, which is based on *Nipype* 1.8.6 (@nipype1; @nipype2; RRID:SCR_002502).

#### Anatomical data preprocessing

The T1-weighted (T1w) image was corrected for intensity non-uniformity (INU) using `N4BiasFieldCorrection` [@n4, ANTs 2.4.3], and used as an anatomical reference throughout the workflow. The anatomical reference image was reoriented into AC-PC alignment via a 6-DOF transform extracted from a full Affine registration to the MNI152NLin2009cAsym template. A full nonlinear registration to the template from AC-PC space was estimated via symmetric nonlinear registration (SyN) using antsRegistration. Brain extraction was performed on the T1w image using SynthStrip [@hoopes_synthstrip_2022] and automated segmentation was performed using SynthSeg [@synthseg1, @synthseg2] from FreeSurfer version 7.3.1. 

#### Diffusion data preprocessing

Any images with a b-value less than 100 s/mm^2 were treated as a *b*=0 image. Denoising using `patch2self` [@patch2self] was applied with settings based on developer recommendations. After `patch2self`, Gibbs unringing was performed using MRtrix3's `mrdegibbs` [@mrdegibbs]. Following unringing, the mean intensity of the DWI series was adjusted so all the mean intensity of the b=0 images matched across eachseparate DWI scanning sequence. B1 field inhomogeneity was corrected using `dwibiascorrect` from MRtrix3 with the N4 algorithm [@n4] after corrected images were resampled.

FSL (version None)'s eddy was used for head motion correction and Eddy current correction [@anderssoneddy]. Eddy was configured with a $q$-space smoothing factor of 10, a total of 5 iterations, and 1000 voxels used to estimate hyperparameters. A linear first level model and a linear second level model were used to characterize Eddy current-related spatial distortion. $q$-space coordinates were forcefully assigned to shells. Field offset was attempted to be separated from subject movement. Shells were aligned post-eddy. Eddy's outlier replacement was run [@eddyrepol]. Data were grouped by slice, only including values from slices determined to contain at least 250 intracerebral voxels. Groups deviating by more than 4 standard deviations from the prediction had their data replaced with imputed values. 

Data was collected with reversed phase-encode blips, resulting in pairs of images with distortions going in opposite directions. FSL's TOPUP [@topup] was used to estimate a susceptibility-induced off-resonance field based on b=0 reference images with reversed phase encoding directions. The TOPUP-estimated fieldmap was incorporated into the Eddy current and head motion correction interpolation. Final interpolation was performed using the `jac` method. 

Several confounding time-series were calculated based on the preprocessed DWI: framewise displacement (FD) using the implementation in *Nipype* [following the definitions by @power_fd_dvars]. The head-motion estimates calculated in the correction step were also placed within the corresponding confounds file. Slicewise cross correlation was also calculated. The DWI time-series were resampled to ACPC, generating a *preprocessed DWI run in ACPC space* with 1.7mm isotropic voxels.


Many internal operations of *QSIPrep* use *Nilearn* 0.10.1 [@nilearn, RRID:SCR_001362] and *Dipy* [@dipy]. For more details of the pipeline, see [the section corresponding to workflows in *QSIPrep*'s documentation](https://qsiprep.readthedocs.io/en/latest/workflows.html "QSIPrep's documentation").

### Citations

If you use these products in your analyses, please cite the relevant papers written by members [TReNDS](https://trendscenter.org/data/).

{{< include _snippets/a2cps_citations.qmd >}}

When using neuroimaging derivatives, please also cite @sadil_acute_2024.
