
```{r setup}
#| include: false
library(readr)
```

# Orientation Distribution Function Reconstruction

One of the primary aims of collecting diffusion MRI data is to estimate the voxelwise Orientation Distribution Fuctions. These functions describe how water diffuses within each voxel. There are many different methods for reconstructing such functions. The A2CPS project relies on two methods, one that produces regional summary metrics, and another for tractography. This kit describes the former.

## Starting Project

### Locate Data

{{< include _snippets/mri-location.qmd >}}

These outputs are under `derivatives/qsirecon_fsl_dtifit`. There are three groups of outputs.

```bash
#| eval: false
$ ls qsirecon_fsl_dtifit
dtifit  qsirecon-fsl  split_shells
```

These outputs were generated in sequence. First, the qsirecon-fsl were generated by the qsirecon workflow [`reorient_fslstd`](https://qsirecon.readthedocs.io/en/latest/builtin_workflows.html#reorient-fslstd), which takes the outputs of @sec-qsiprep and reorients them into the format that is expected by the [FSL Diffusion Toolbox](https://fsl.fmrib.ox.ac.uk/fsl/docs/diffusion/index.html). For details on the organization of that folder, see [the QSIRecon documentation](https://qsirecon.readthedocs.io/en/latest/outputs.html). Then, the `split_shells` outputs were generated. They contain the reoriented outputs, but split into different bvals. For example

```{bash}
#| eval: false
$ tree -l qsirecon_fsl_dtifit/split_shells/sub-10010
qsirecon_fsl_dtifit/split_shells/sub-10010
└── ses-V1
    └── dwi
        ├── sub-10010_ses-V1_acq-b0_space-T1w_dwi.bval 
        ├── sub-10010_ses-V1_acq-b0_space-T1w_dwi.bvec 
        ├── sub-10010_ses-V1_acq-b0_space-T1w_dwi.nii.gz 
        ├── sub-10010_ses-V1_acq-b1000_space-T1w_dwi.bval 
        ├── sub-10010_ses-V1_acq-b1000_space-T1w_dwi.bvec 
        ├── sub-10010_ses-V1_acq-b1000_space-T1w_dwi.nii.gz 
        ├── sub-10010_ses-V1_acq-b2000_space-T1w_dwi.bval 
        ├── sub-10010_ses-V1_acq-b2000_space-T1w_dwi.bvec 
        ├── sub-10010_ses-V1_acq-b2000_space-T1w_dwi.nii.gz 
        ├── sub-10010_ses-V1_acq-b3000_space-T1w_dwi.bval 
        ├── sub-10010_ses-V1_acq-b3000_space-T1w_dwi.bvec 
        ├── sub-10010_ses-V1_acq-b3000_space-T1w_dwi.nii.gz 
        ├── sub-10010_ses-V1_acq-b500_space-T1w_dwi.bval 
        ├── sub-10010_ses-V1_acq-b500_space-T1w_dwi.bvec 
        └── sub-10010_ses-V1_acq-b500_space-T1w_dwi.nii.gz 

2 directories, 15 files
```

Finally, the `dtifit` outputs were generated by running FSL's [`dtifit`](https://fsl.fmrib.ox.ac.uk/fsl/docs/diffusion/dtifit.html) on different combinations of the bvalues.

```{bash}
#| eval: false
$ ls qsirecon_fsl_dtifit/dtifit/
b1000  b2000  b3000  multishell
```

Most of those are self-explanatory (e.g., the `b1000` subfolder contains the fits with the b1000 shell). The `multishell` outputs were generated from the full dMRI scan (that is, all shells). Which of these outputs to use is up to the individual researcher. According to the ABCD, the protocol and analysis plan on which A2CPS dMRI is based, [many researchers may prefer the multishell outputs](https://docs.abcdstudy.org/latest/documentation/imaging/type_dmri.html#mr_y_dti). That said, the tensor model is known to fit poorly to diffusion data with bvalues larger than about 1500 [@henriques_2021_diffusional, @jensen_2005_diffusional], which is a majority of this sequence. Given that, some researchers may prefer the b1000 outputs, but note that these are based on only 15 directions. 

The contents of each of the `dtifit` subfolders are in a "bidsish" organization, containing [the standard outputs of `dtifit`](https://fsl.fmrib.ox.ac.uk/fsl/docs/diffusion/dtifit.html#outputs-of-dtifit), grouped by subject and session.

```{bash}
#| eval: false

# within qsirecon_fsl_dtifit/dtifit/b1000
$ tree sub-10220
sub-10220
└── ses-V1
    └── dwi
        ├── sub-10220_ses-V1_acq-b1000_space-T1w_dwi_FA.nii.gz
        ├── sub-10220_ses-V1_acq-b1000_space-T1w_dwi_L1.nii.gz
        ├── sub-10220_ses-V1_acq-b1000_space-T1w_dwi_L2.nii.gz
        ├── sub-10220_ses-V1_acq-b1000_space-T1w_dwi_L3.nii.gz
        ├── sub-10220_ses-V1_acq-b1000_space-T1w_dwi_MD.nii.gz
        ├── sub-10220_ses-V1_acq-b1000_space-T1w_dwi_MO.nii.gz
        ├── sub-10220_ses-V1_acq-b1000_space-T1w_dwi_S0.nii.gz
        ├── sub-10220_ses-V1_acq-b1000_space-T1w_dwi_sse.nii.gz
        ├── sub-10220_ses-V1_acq-b1000_space-T1w_dwi_tensor.nii.gz
        ├── sub-10220_ses-V1_acq-b1000_space-T1w_dwi_V1.nii.gz
        ├── sub-10220_ses-V1_acq-b1000_space-T1w_dwi_V2.nii.gz
        └── sub-10220_ses-V1_acq-b1000_space-T1w_dwi_V3.nii.gz

2 directories, 12 files
```

### Extract Data

Most of these outputs are nifti images, and so any tool capable of reading them will work. Some neuroimaging graphical user interfaces also have built in tools for viewing the tensors. For example, by default the FSL viewer [`fsleyes`](https://open.oxcin.ox.ac.uk/pages/fsl/fsleyes/fsleyes/userdoc/) will accept as input a folder with `dtifit` outputs and by default [display the estimated tensors](https://open.oxcin.ox.ac.uk/pages/fsl/fsleyes/fsleyes/userdoc/overlays.html#tensor).

```{bash}
#| eval: false
$ fsleyes dwi
```

There are several options for refining the display. For example, [fsleyes can also produce variations on color FA maps](https://open.oxcin.ox.ac.uk/pages/fsl/fsleyes/fsleyes/userdoc/overlays.html#vector).

## Considerations While Working on the Project

### Data Generation 

These outputs were generated by the [qsirecon-fsl_dtifit_app](https://github.com/a2cps/mri_imaging_pipeline/tree/master/qsirecon-fsl_dtifit_app). As discussed above, the orientation distribution functions were reconstructed with the standard diffusion tensor imaging model, as estimated by FSL's [dtifit](https://fsl.fmrib.ox.ac.uk/fsl/docs/diffusion/dtifit.html) (using the weighted-least squares option). 

For a good general introduction to DTI, see [the QSIRecon documentation](https://qsirecon.readthedocs.io/en/latest/models/dti.html#diffusion-tensor-imaging-dti). 

Note that the tensor model is known to fit poorly to diffusion data with bvalues larger than about 1500 [@henriques_2021_diffusional, @jensen_2005_diffusional]. Several advanced models have been proposed, and the A2CPS neuroimaging DIRC is actively testing these. Outputs from another model are expected to be available in the release 4 series.

### Variability Across Scanners

{{< include _snippets/mri-scanner-variability.qmd >}}

### Data Quality

{{< include _snippets/mri-qc.qmd >}}

### Citations

The standard DTI reference is @basser1994mr. These outputs used a workflow from QSIRecon, 

{{< include _snippets/a2cps_citations.qmd >}}

When using neuroimaging derivatives, please also cite @sadil_acute_2024.

